"""empty message

Revision ID: 13aafa34d101
Revises: 382b49592b9d
Create Date: 2024-07-15 17:17:16.207486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13aafa34d101'
down_revision = '382b49592b9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('icon')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
