""" Initial migration

Revision ID: 13aafa34d101
Revises: 
Create Date: 2024-07-15 16:06:07.337392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13aafa34d101'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
