"""empty message

Revision ID: 402dc7bf57dd
Revises: 13aafa34d101
Create Date: 2024-07-18 11:56:27.185890

"""
from alembic import op
import sqlalchemy as sa
from database import db


# revision identifiers, used by Alembic.
revision = '402dc7bf57dd'
down_revision = '13aafa34d101'
branch_labels = None
depends_on = None


def upgrade():
    db.drop_all()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('icon')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
