"""empty message

Revision ID: 83ede3ac8a37
Revises: c7feae971e82
Create Date: 2024-07-20 15:20:30.100361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ede3ac8a37'
down_revision = 'c7feae971e82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flares', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
