"""empty message

Revision ID: e7511c6ea2f0
Revises: 83ede3ac8a37
Create Date: 2024-07-27 19:26:54.114732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7511c6ea2f0'
down_revision = '83ede3ac8a37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spoons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spoons', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('spoons')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spoons', sa.INTEGER(), autoincrement=False, nullable=False))

    op.drop_table('spoons')
    # ### end Alembic commands ###
