"""empty message

Revision ID: 94d0ad8f8ef7
Revises: e58337a85935
Create Date: 2024-07-12 18:24:59.426479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94d0ad8f8ef7'
down_revision = 'e58337a85935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(100), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(100), nullable=False))
        batch_op.drop_column('spoons_used')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spoons_used', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('profile_pic')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
